FROM tomcat:9.0-jre17
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war

# Set Tomcat to listen on port 8082
RUN sed -i 's/port="8080"/port="8082"/' /usr/local/tomcat/conf/server.xml

EXPOSE 8082
CMD ["catalina.sh", "run"]
# Build stage
# FROM maven:3.9.6-eclipse-temurin-17 AS build
# WORKDIR /app
# COPY pom.xml .
# COPY src ./src
# RUN mvn clean package -DskipTests

# Run stage